### ISSUE TITLE
It's using Paho library inside?

### ISSUE THREAD

**Issue by mmehdi** [adonmo/killerbee#1]
I am confused why are you using Paho library inside your project?

`dependencies {

    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.9'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation "androidx.core:core-ktx:$rootProject.ext.ktx_version"
    implementation "androidx.appcompat:appcompat:$rootProject.ext.app_compat_version"
    implementation "androidx.constraintlayout:constraintlayout:$rootProject.ext.constraintLayoutVersion"
    testImplementation "junit:junit:$rootProject.ext.junitVersion"
    androidTestImplementation "androidx.test.ext:junit:$rootProject.ext.androidJunitVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$rootProject.ext.espressoVersion"
    testImplementation 'io.mockk:mockk:1.11.0'

    api "org.eclipse.paho:org.eclipse.paho.client.mqttv3:${rootProject.ext.clientVersion}"
}`

**Comment by thelordoflite** [comment]
@mmehdi Killerbee works on top of paho ```Java``` client. Killerbee is just a re-implementation of paho ```Android``` client and just like its predecessor it also internally uses ```Java``` client by Paho.

This project was targeted at Android level interfaces that we intended to change. The base java code that handles MQTT specifics was not our focus.
